### PR TITLE
Fix directory size for non-empty 'statusline'

### PR DESCRIPTION
**Pull request by dimonomid**

### CODE REVIEW

**Comment by dimonomid** [comment]
My previous commit was not complete indeed. :)

Actually, `get_fentry_size` is not specific to statusline, so it should probably be factored out into more generic place and used across the rest of the codebase, but having little context of the project so far, I keep this change localized to statusline.

**Comment by xaizek** [comment]
Looks like I failed to test it properly since I use `%E` macro. By the way, it's right below case statement for `%s` and uses already existing `get_file_size_by_entry()` function... I merged it way too fast :)

**Comment by dimonomid** [comment]
Good point; I missed `get_file_size_by_entry()`. Updated.

**Comment by xaizek** [comment]
Thanks!

**Pull request merged**
