### PR TITLE
Removed favicon repo of tornax (me)

### PR DESCRIPTION
**Pull request by TornaxO7**
First of all: Thank you for accepting my first pull request! I appreciate it :) <br>
I saw that you edit my pull request and I was impressed of the other favicon repo. My repo hasn't that many favicons so I'd like to remove it as well as from this README.md

### CODE REVIEW

**Comment by xaizek** [comment]
There are too many unnecessary changes. Could you edit the file manually? (I think you used some editor.) Also please drop the link from the `README` file as well.

**Comment by TornaxO7** [comment]
Oh damn it xD `coc-format` did that. Pls give me a minute.

**Comment by TornaxO7** [comment]
- Removed the `README` file (not the `README.md` file!)
- Removed the unnecessary markdown file formatting

**Comment by TornaxO7** [comment]
Wait what? How did the build failed? I just changed the README.md file and removed the README file?

**Comment by xaizek** [comment]
`README` is part of the documentation. Don't remove it, just remove one link from it.

**Comment by TornaxO7** [comment]
- Added the README back
- Removed link in README and README.md

**Comment by xaizek** [comment]
LGTM now, thanks!

**Pull request merged**
