### PR TITLE
Disable extended keys above KEY_MAX so that esc-codes can be used in mappings

### PR DESCRIPTION
**Pull request by mckellygit**
Hi,

Thank you for awesome vifm.
Here is a PR for issue https://github.com/vifm/vifm/issues/634 - if you find it useful.

thx,
-m

### CODE REVIEW

**Comment by mckellygit** [comment]
Hi,
I tested this, but it does not work.  The esc-code mappings for \<c-down\> and some others now no longer work.
I used:
```
   use_extended_names(false);
```
instead of my loop of keyok(i, false) at the same location in the code.

**Comment by mckellygit** [comment]
I just added a word to the comment

**Comment by xaizek** [comment]
Last request: please try calling `use_extended_names(false);` before `initscr()`. If it doesn't work, then I guess it doesn't do what I think it does and it's of no use.

I've also found [an answer](https://stackoverflow.com/a/29730981/1535516) by Thomas Dickey, which talks about `define_key()` function. Maybe it could be used in the future to avoid mapping `<esc>...` sequences. (This is more of a note to myself.)

**Comment by mckellygit** [comment]
Hi,

Yes! - calling it earlier, before initscr() works!

And yes, the harder way - we could have defined our own keys with define_key() -
#define KEY_CDOWN 5002
define_key("\033[1;5B", KEY_CDOWN); 
Even better is to query for keynames such as kDN5 etc and then you know the capability and dont have to hard-code any esc codes.
But the use_extended_names(false) is best.
thx,
-m

**Comment by mckellygit** [comment]
Do you want me to update the PR or just close it ?

**Comment by mckellygit** [comment]
Probably should wrap the call in an ifdef for the ncurses version/usage, as use_extended_names() might not be in all curses

**Comment by xaizek** [comment]
Great! Thanks a lot for testing.

Yes, it needs a `NCURSES_EXT_FUNCS` `#ifdef` around it. Update the PR, no need to close it.

`kDN5` isn't a standard name, so looking it up doesn't sound right. Hard-coding will depend on a terminal also. I was thinking about adding a command like `:newkey <c-down> <esc>[1;5B` after which `qnoremap <c-down> ...` would make sense.

**Comment by mckellygit** [comment]
Updated PR and squashed.
I like your two-step approach so esc codes are user/config-defined, it would be a good alternative/addition one day.
thx,
-m

**Comment by xaizek** [comment]
Merged, thank you!

**Comment by mckellygit** [comment]
Thanks.
Perhaps it should be 
#if defined(NCURSES_EXT_FUNCS) && defined(NCURSES_XNAMES)
but I dont think it really matters much.
-m

**Comment by mckellygit** [comment]
@xaizek hi,
Just some info, we tried this same thing in tig, removing the keyok(false) code and calling use_extended_names(false) instead.
It works, but it was discovered that mouse clicks no longer work on a Mac with Terminal.  Mouse seems ok in some other terms though.
I just wanted to mention this if it maybe is useful one day.

**Comment by xaizek** [comment]
Thanks, I'll update the comment just in case (I could never make the mouse work adequately).

**Comment by mckellygit** [comment]
From koutcher -
The problem occurs with xterm (and derived) terminal descriptions. It seems to be linked to changes introduced in ncurses 6.1 regarding kmous capability.

**Pull request merged**
