### PR TITLE
new align option

### PR DESCRIPTION
**Pull request by cosminadrianpopescu**
Added the AT_FILE alignment option. This is just as left, but when the text exceeds the boundaries, then the alignment will be switch to right. Like this, the file name will always be visible. The name is not very inspired, maybe you have a better idea. 

Also fixed the logging option. The /var/log/vifm-startup-log was hard coded for the log location, and because of the permissions, it was not created. Now the log file is saved in ~/.vifm/vifm-startup-log.

### CODE REVIEW

**Comment by xaizek** [comment]
> Added the AT_FILE alignment option. This is just as left, but when the text exceeds the boundaries, then the alignment will be switch to right. Like this, the file name will always be visible. The name is not very inspired, maybe you have a better idea.

Thanks, this might be useful, especially in custom views.

> Also fixed the logging option. The /var/log/vifm-startup-log was hard coded for the log location, and because of the permissions, it was not created. Now the log file is saved in ~/.vifm/vifm-startup-log.

We can't use `~/.vifm` at that point because actual location of configuration is unknown yet, otherwise we wouldn't need separate startup-log file and could use regular one. I'll probably change that to location under temporary directory concatenated with user name. I think I saw this issue, but wasn't sure such rights are on every distribution, thanks for bringing it up.

**Comment by cosminadrianpopescu** [comment]
> We can't use ~/.vifm at that point because actual location of configuration is unknown yet, otherwise we wouldn't need separate startup-log file and could use regular one. I'll probably change that to location under temporary directory concatenated with user name. I think I saw this issue, but wasn't sure such rights are on every distribution, thanks for bringing it up.

Then I can implement something like --logging=<path-to-log>

**Comment by xaizek** [comment]
> Then I can implement something like --logging=<path-to-log>

Hm, that's a valid option.  Maybe don't log anything at startup by default (it's useless in most cases anyway) and do log the rest to `<config>/log`, but if `<path-to-log>` is provided log everything to that location?

**Comment by cosminadrianpopescu** [comment]
> Hm, that's a valid option. Maybe don't log anything at startup by default (it's useless in most cases anyway) and do log the rest to <config>/log, but if <path-to-log> is provided log everything to that location?

Ok. I will implement something like this.

**Comment by xaizek** [comment]
I've merged in align part. Renamed it to "dynamic" as real alignment is chosen dynamically.

Thanks!

**Pull request closed without merging**
