### PR TITLE
Provide AppImage build on each tag/release

### PR DESCRIPTION
**Pull request by michaellee8**
It took me a day to finally get latest version to put this up together. It is tested to work with distro as old as Ubuntu 16.04 LTS. I have manually compiled libncursesw6 so that it will work even for 256 colors terminals (like xterm-256color). It also uses its own terminfo database so theoretically it should work as long as there are libc, for example alpine linux.

Note that you will need to changed the deploy section with your own encrypted key and maybe other things to work in your repo.

### CODE REVIEW

**Comment by xaizek** [comment]
I've changed the script quite significantly. Could you check that result still works for you?

[vifm-x86_64.AppImage.log](https://github.com/vifm/vifm/files/5540976/vifm-x86_64.AppImage.log)

(".log" extension is there just for GitHub.)

**Comment by michaellee8** [comment]
> I've changed the script quite significantly. Could you check that result still works for you?
> 
> [vifm-x86_64.AppImage.log](https://github.com/vifm/vifm/files/5540976/vifm-x86_64.AppImage.log)
> 
> (".log" extension is there just for GitHub.)

Great, it looks good to me, can I have a look at what changes did you make?

**Comment by xaizek** [comment]
I'll push them along with source code changes soon.

**Comment by michaellee8** [comment]
> I'll push them along with source code changes soon.

Glad to hear that.

**Pull request closed without merging**
