### PR TITLE
Implement :histnext / :histprev

### PR DESCRIPTION
**Pull request by dimonomid**

### CODE REVIEW

**Comment by dimonomid** [comment]
I realized that I didn't add anything to docs, let me amend it..

**Comment by dimonomid** [comment]
Done.

Resolves https://github.com/vifm/vifm/issues/283

**Comment by xaizek** [comment]
Thanks.

**Comment by dimonomid** [comment]
And thank you for accepting and making all the related changes; hopefully next time I'll do more of that burden myself.

**Comment by dimonomid** [comment]
Ah and by the way, I got used to the workflow when we review each other's PRs and make comments asking the PR author to perform all the needed changes, so feel free to do that :) I personally like https://reviewable.io/ , instead of the built-in github reviewing tool (because the github's thing is more of a commenting tool, rather than a reviewing one; I could get into many details but I think it's irrelevant for now)

**Comment by xaizek** [comment]
Most of open source contributions aren't recurring, so it's often easier to do necessary changes yourself instead of going back and forth until everything is done :)

In case you didn't notice there are several checklists on [the wiki](https://wiki.vifm.info/index.php?title=Development#Instructions), which I use myself to do not forget all the places that need updates (my local version might differ a bit though, will need to sync).

**Comment by dimonomid** [comment]
Yes I missed these checklists indeed, thanks.

**Pull request merged**
