### PR TITLE
adding second screenshot to the README

### PR DESCRIPTION
**Pull request by TornaxO7**
This makes `vifm` a little bit more attractive in my opinion.

### CODE REVIEW

**Comment by xaizek** [comment]
Thanks!

**Comment by RayZ0rr** [comment]
Hey, can you tell me how to get that 3-pane view in vifm (as shown in second screenshot)?

**Comment by TornaxO7** [comment]
@RayZ0rr aye!
You just need the following lines if I'm remembering it right (I haven't touched my vifm config for a year now):
```vifm
set millerview
set milleroptions="lsize:1,csize:2,rsize:0,rpreview:all"
fileviewer *.c,*.[ch]pp,*.h highlight -O ansi --syntax c %c
fileviewer *.ja[rv][a] highlight -O ansi --syntax java %c
fileviewer Makefile,Makefile.* highlight -O ansi -s dante --syntax make %c
fileviewer *.py highlight -O ansi --syntax python --progress %c
fileviewer *.vifm,vifmrc,*.vim,vimrc highlight -O ansi --syntax vimscript --progress %c
fileviewer *.ts highlight -O ansi --syntax ts --progress %c
fileviewer *.json highlight -O ansi --syntax json --progress %c
fileviewer *.txt highlight -O ansi --syntax txt --progress %c
fileviewer *.lua highlight -O ansi --syntax lua --progress %c
fileviewer *.tex highlight -O ansi --syntax tex --progress %c
fileviewer *.sh highlight -O ansi --syntax sh --progress %c
fileviewer *.dart highlight -O ansi --syntax dart --progress %c
fileviewer *.asm,*.s highlight -O ansi --syntax assembler --progress %c
fileviewer *.rs, highlight -O ansi --syntax rust --progress %c
fileviewer *.toml, highlight -O ansi --syntax toml --progress %c
```
this should be enough I think.

**Comment by xaizek** [comment]
Also need to active quickview with `:view!` or change `rsize:0` and use one pane with `:only`.

**Pull request merged**
