### PR TITLE
Add shell completion for fish-shell

### PR DESCRIPTION
**Pull request by FollieHiyuki**
Completion for '+' argument is not implemented as I can't figure out how to do so. Help is welcomed.

### CODE REVIEW

**Comment by FollieHiyuki** [comment]
I got completion for '+' working, thanks to some advice in the linked issue.

Some drawbacks:
- The first time the user invokes completion (by typing `vifm <TAB>`) it is pretty slow (I'm looping through all available command strings and their descriptions).
- If the user types `vifm +<TAB>` as the first time the completion is invoked, it will only complete commands with '+' element in them (g++, clang++, ...). Every completion afterwards will be broken (as completion for '+' is now cached).

**Comment by xaizek** [comment]
Thanks for this. I think you misunderstood `-c` and `+`. They accept Vifm's command-line :commands, not external commands, so you don't really need to complete thier arguments.

**Comment by FollieHiyuki** [comment]
Silly me :)

I don't use `-c` and `+` personally so I have no idea how they work. The description `run <command> on startup` is kind of misleading for me.

On that note I think it will be nice having a way for `vifm` to print out its available commands (maybe with `vifm --available-commands` or something) so we can fetch it to the completion?

**Comment by xaizek** [comment]
Thanks, merged.

> On that note I think it will be nice having a way for `vifm` to print out its available commands (maybe with `vifm --available-commands` or something) so we can fetch it to the completion script.

`--list-commands` (for consistency with `--list-servers`) can be added, but there is a reason why you don't know how to complete `+c`, it's useful for scripts rather than interactively.

**Pull request merged**
