### PR TITLE
README: Removed link to pull request to vifmimg

### PR DESCRIPTION
**Pull request by TornaxO7**
My pull request has been merged. No need anymore to let the link stay there. See here for more information: https://github.com/cirala/vifmimg/pull/17

### CODE REVIEW

**Comment by xaizek** [comment]
Please also remove
```
[vifmimg-pr]: https://github.com/cirala/vifmimg/pull/17
```

**Comment by TornaxO7** [comment]
Should be done now :)

**Comment by xaizek** [comment]
Now you've added Idea project :)

**Comment by TornaxO7** [comment]
oh damn, sorry! That was not supposed to happen. Should be fixed now.

**Comment by xaizek** [comment]
Thanks!

**Pull request merged**
