### PR TITLE
Added example vifmrc-osx in /data

### LINKED ISSUE #83: OSX config options
I have, at this stage, a fairly complete set of OSX-specific config options in my vifmrc, mostly for file launching / viewing, with a few additional bits. If I tidy it up it might make a good starting point for a 'base' example OSX config. Would you have any interest in including OSX options, either commented out in the existing sample vifmrc or as an additional example file? I would be very happy to maintain it, or contribute to it in any way that makes life easier for you! ;)

### PR DESCRIPTION
**Pull request by larryhynes**
This is a start on the example vifmrc-osx file.

I've ommitted or commented the Fuse options. I've removed the `vgrep` command, as I couldn't get it to work! I've included w3m as a fileviewer for web files; personal bias FTW. :smile:  I removed the tudu filetype, and I didn't include the qtcreator filetype: I had a bit of a look around and it looks (from [here](http://stanford.edu/~rawatson/qt/mac_install_gifs/)) like qrcreator is a bit of a major installation on OSX. I've tried to have sane defaults and a good spread of options to give a feel for what's possible. I *think* I matched your code style!

Any comments are welcome, I'm more than happy to tweak this until we feel it's right.

Closes #83.

### CODE REVIEW

**Comment by xaizek** [comment]
> I've included w3m as a fileviewer for web files; personal bias

You might want to look at #82, if you want to preview images via w3m without leaving vifm.

> I've ommitted or commented the Fuse options.

Why completely disable it? There was #75 quite recently, it revealed some issues with FUSE on OS X, but it should work now fine. Maybe leave some example and refer to [OSX FUSE](https://github.com/osxfuse/osxfuse/wiki/FAQ)?

**Comment by larryhynes** [comment]
I've never had any luck with w3m image previews on OSX, and I *have* tried. Interestingly the [Homebrew formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/w3m.rb) explicitly disables images with `--disable-image`.

I'll have a look at the Fuse stuff and add it back in. :)

**Comment by xaizek** [comment]
> Interestingly the Homebrew formula explicitly disables images with --disable-image.

It depends a lot on a terminal, it doesn't work for me with `st` as well, but works fine with `xterm`. w3m relies on specific terminal window update and buffering behaviour, which varies from one terminal to another. Basically terminal shouldn't wipe its background on updates, otherwise images drawn by w3m are cleared so fast you barely can see it in most cases.

**Comment by larryhynes** [comment]
I'm having difficulties getting FUSE to work properly, with a fresh install. I'll keep plugging away at it!

**Comment by xaizek** [comment]
> Are the issues encountered in #75 fixed in vifm Version 0.7.8 as installed by Homebrew?

No, it was fixed only two month ago. I don't use OS X and looks like FUSE isn't popular there, I thought it works the same way as on GNU/Linux :)

**Comment by larryhynes** [comment]
My instinct would be to leave the FUSE stuff out until those fixes are available through Homebrew. Once I can get FUSE working OK here I'll add them back into the example config. You happy with that?

**Comment by xaizek** [comment]
> You happy with that?

Sure, I just thought you're using current version.

**Comment by xaizek** [comment]
Thanks! It looks fine to me now. I'm going to look at it tomorrow once again and then merge.

**Comment by larryhynes** [comment]
No problem! I'll keep an eye on development and maybe propose changes / additions as work progresses and, as I say, once I can get FUSE working here with a release I'll get that back in.

**Comment by xaizek** [comment]
Didn't notice last two commits, so they weren't merged, but I fixed that typo anyway and on OS X this sample file should be installed on first run, so maybe the second commit isn't needed, but can be added separately in case you think it might be useful. As the rest is there, so I'm closing this.

By the way, you might want to read [this post on git commit messages](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html), it explains why it's better to write commit messages in present tense, which seems to make sense.

**Comment by larryhynes** [comment]
>By the way, you might want to read [this post on git commit messages](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html), it explains why it's better to write commit messages in present tense, which seems to make sense.

Good thinking; it's something I've meant to improve on, but as most of my commit messges are to myself there isn't a whole lot of motivation for it! I shall resolve to improve. :)

**Pull request closed without merging**
